### ISSUE TITLE
[Feature request] Keep skin after quit to main menu

### ISSUE THREAD

**Issue by Jing-Linux** [PrashantMohta/HollowKnight.CustomKnight#10]
Can you implement a feature that keeps the skin selected after quit to main menu and load another game? That would be nice to have since I don't have to select my skin every time after I quit to menu or switch save.

**Comment by PrashantMohta** [comment]
> Can you implement a feature that keeps the skin selected after quit to main menu and load another game? That would be nice to have since I don't have to select my skin every time after I quit to menu or switch save.

yeah this is a requested feature that i plan to make a part of next release !
