### ISSUE TITLE
[Feature Request] Change more things

### ISSUE THREAD

**Issue by ygsbzr** [PrashantMohta/HollowKnight.CustomKnight#11]
I hope that we can replace the sprite of something in Dontdestroyonload, like super spitter in Collector's Jar,that's really fun

**Comment by ygsbzr** [comment]
and how can I skin some boss like xero in RestingGround

**Comment by PrashantMohta** [comment]
I have not checked them specifically, but swapper should allow skinning both of these. have you tried with it?

**Comment by ygsbzr** [comment]
Yes,I tried named the image"ghost warrior xero",but it doesn't work

**Comment by ygsbzr** [comment]
And I cant swap things from GlobalPool like super spitter in GG_Collector_V

**Comment by PrashantMohta** [comment]
Just checked, it seems xero is not part of the main scene and that might be causing this i'll look into both this and Dontdestroyonload. thanks for letting me know about this!
