### ISSUE TITLE
[Feature Request] Seperated sprites

### ISSUE THREAD

**Issue by Jing-Linux** [PrashantMohta/HollowKnight.CustomKnight#24]
I hope that we can use one complete skin with another skin that only modifies some parts, like HUD, Spells, Skills while the the skin that only modify some parts overwrites the complete skin. Much appreciated if this makes into a real feature!

**Comment by PrashantMohta** [comment]
CK 3.0 adds support for this in the Mod menu in the form of alternate sheets, setting those up is left up to the user or the skin author. Note: this will still work at a file level which means everything that is on a single file will require editing the files themselves.
