### ISSUE TITLE
A glitch?

### ISSUE THREAD

**Issue by P0ggerCat** [PrashantMohta/HollowKnight.CustomKnight#29]
So i install customknight, nothing but knight skin works, like custom hud, spell skins, magic skins, etc, is there a way to fix it? ![image](https://user-images.githubusercontent.com/89139444/217002579-1d6d9379-a8b2-477b-83b3-7e10fd490183.png)

**Comment by P0ggerCat** [comment]
It's so strange, crystal heart skin effects are there but vengeful spirit's arent???

**Comment by MurdoMaclachlan** [comment]
If the Knight & Crystal Dash are reskinned but nothing else is, that would suggest to me you are missing most of the skin's image files. (Textures for Cdash & the Knight are in the same file.)

This looks like the Little Grimm skin - under its subfolder in `/Custom Knight/Skins/`, there should be somewhere in the vacinity of 30 image files for the whole skin, going by my installation.
