### ISSUE TITLE
when using the area changing skins the dont work what do i do

### ISSUE THREAD

**Issue by ShmootyDev66** [PrashantMohta/HollowKnight.CustomKnight#38]

**Comment by DwarfWoot** [comment]
Custom Knight itself doesn't support Area Changing skins. I believe that you are thinking of "CustomKnightPlus" which is a different mod, that adds some extra options for skins to use. If you want technical support with Mods, then you should probably join the HK Modding Discord server (linked in the Custom Knight Mods Menu iirc), and you can create a #support post there.

**Comment by ShmootyDev66** [comment]
custom knight plus isnt working

**Comment by ShmootyDev66** [comment]
nvm
