### ISSUE TITLE
[Feature Request] - Particle Effects

### ISSUE THREAD

**Issue by Adomin8er** [PrashantMohta/HollowKnight.CustomKnight#39]
I'm trying to modify the colors for "Fury of the Fallen" when activated, but I've been unable to dump it nor find it in the hashcache.json (though this might be because I don't know its proper name). I've reached out on the HK Modding discord and they said that if a particle effect can't be found in the default skin folder, then it can't be changed. Would it be possible to enable particle effect dumping?

**Comment by PrashantMohta** [comment]
CK3.0 adds this behind a flag. as this feature is in early preview. let me know if that solves your usecase.
