### ISSUE TITLE
skins not working after latest upfate

### ISSUE THREAD

**Issue by Samrox2004** [PrashantMohta/HollowKnight.CustomKnight#40]
when I go to enable a skin it does nothing 

it says its enabling the skin but nothing changes and I'm suck on the default skin

here is a list of the skins I have
![20240428030905_1](https://github.com/PrashantMohta/HollowKnight.CustomKnight/assets/143651895/e9a0f796-22bc-4ac7-97a1-ecadcaddb2f1)

**Comment by DwarfWoot** [comment]
When you are in the Custom Knight menu in the pause menu, it actually has a button for if you need help with using the mod, which will link you to the Modding Discord. There we have resources for common issues, and can better help you resolve them.

**Comment by Samrox2004** [comment]
It seems to be an issue with the moresaves mod.

Need the moresaves mod to update and fix it.

Thanks for the help.
