### ISSUE TITLE
a problem about custom knight

### ISSUE THREAD

**Issue by aloooooooone** [PrashantMohta/HollowKnight.CustomKnight#42]
<img width="161" alt="屏幕截图 2024-05-10 171504" src="https://github.com/PrashantMohta/HollowKnight.CustomKnight/assets/169443636/0bdfcba1-86df-41de-a3d0-9b87e727eaab">

**Comment by LostDreamtab** [comment]
такая же проблема

**Comment by PrashantMohta** [comment]
Please reach out at the modding discord #support channel https://discord.com/invite/RppAb2vNqz
