### ISSUE TITLE
Не хочет работать Custom Knight

### ISSUE THREAD

**Issue by LostDreamtab** [PrashantMohta/HollowKnight.CustomKnight#44]
Какие танцы с бубном нужны для того чтобы просто поиграть со своим скином?

**Comment by LostDreamtab** [comment]
> Какие танцы с бубном нужны для того чтобы просто поиграть со своим скином?

**Comment by PrashantMohta** [comment]
Please reach out at the modding discord #support channel https://discord.com/invite/RppAb2vNqz
